output_dir := "build"

[positional-arguments]
@make *args:
    make "$@"

clean:
    make clean
flash:
    make flash
flash-chiperase:
    make flash-chiperase
flash-recover:
    make flash-recover
reset:
    make reset

format:
    cd app-core && cargo fmt
    cd net-core && cargo fmt
alias fmt := format

@attach-app:
    probe-rs attach --chip nRF5340_xxAA "{{ output_dir }}/app.elf"
@attach-net:
    probe-rs attach --chip nRF5340_xxAA "{{ output_dir }}/net-core.elf"
@serial *args:
    cd serialtest && cargo run {{ args }}
