target    := "thumbv7em-none-eabihf"
profile   := "release"
bin       := "dongle-fw"

# nrfutil
hw        := "52"
# SoftDevice requirement for DFU package. Set to 0x00 when no SoftDevice is present.
sd_req    := "0x00"
app_ver   := "1"
key_file  := ""

# Serial
dfu_port  := "COM20"
# dfu_port  := "COM65"
baud      := "115200"
dev_port  := "COM14"

ROOT      := "."

default: flash

hex:
    echo "==> Converting to HEX (cargo objcopy)"; \
    cargo objcopy --config .cargo/config.toml --bin {{bin}} --target {{target}} --{{profile}} -- -O ihex "{{ROOT}}/target/{{target}}/{{profile}}/{{bin}}.hex"; \
    echo "HEX: {{ROOT}}/target/{{target}}/{{profile}}/{{bin}}.hex"; \
    head -n 2 "{{ROOT}}/target/{{target}}/{{profile}}/{{bin}}.hex" || true

dfu-pkg: hex
    echo "==> Creating DFU package (nrfutil)"; \
    PKG="{{ROOT}}/target/{{target}}/{{profile}}/{{bin}}-dfu.zip"; \
    APP="{{ROOT}}/target/{{target}}/{{profile}}/{{bin}}.hex"; \
    if [ -n "{{key_file}}" ]; then nrfutil pkg generate --hw-version {{hw}} --application-version {{app_ver}} --sd-req {{sd_req}} --application "$APP" --key-file "{{key_file}}" "$PKG"; else nrfutil pkg generate --hw-version {{hw}} --application-version {{app_ver}} --sd-req {{sd_req}} --application "$APP" "$PKG"; fi; \
    echo "PKG: $PKG"

flash: dfu-pkg
    echo "==> DFU over serial port {{dfu_port}} (baud {{baud}})"; \
    PKG="{{ROOT}}/target/{{target}}/{{profile}}/{{bin}}-dfu.zip"; \
    nrfutil dfu serial -pkg "$PKG" -p "{{dfu_port}}" -b "{{baud}}" --flow-control true; \
    echo "Done."

paths:
    echo "ELF: {{ROOT}}/target/{{target}}/{{profile}}/{{bin}}"; \
    echo "HEX: {{ROOT}}/target/{{target}}/{{profile}}/{{bin}}.hex"; \
    echo "ZIP: {{ROOT}}/target/{{target}}/{{profile}}/{{bin}}-dfu.zip"

attach:
    defmt-print --log-format oneline -e {{ROOT}}/target/thumbv7em-none-eabihf/release/dongle-fw serial --dtr --path {{dev_port}}
