[unstable]
#build-std = ["core"]
#build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nrf5340_xxAA"

rustflags = [
  # Code-size optimizations.
  #"-Z", "trap-unreachable=no",
  #"-C", "no-vectorize-loops",
  "-C", "force-frame-pointers=yes",
]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "info"
