[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.3"
image = { version = "0.24.8", default-features = false, features = ["png"] }
serialport = { version = "4.3.0", features = ["usbportinfo-interface"] }
