[package]
name = "viewer"
version = "0.1.0"
edition = "2021"
default-run = "viewer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
ggez = "0.9.3"
image = { version = "0.24.8", default-features = false, features = ["png"] }
opencv = "0.91.1"
serialport = { version = "4.3.0", features = ["usbportinfo-interface"] }
