[package]
edition = "2021"
name = "donger-firmware"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[features]
default = ["vm2"]
mcuboot = ["cortex-m-rt/set-sp", "cortex-m-rt/set-vtor"]
vm2 = ["embassy-nrf/nrf52840"]
atslite-1-1 = ["embassy-nrf/nrf5340-app-s"]


[dependencies]
embassy-executor = { version = "0.5.0", features = ["arch-cortex-m", "defmt", "executor-thread", "integrated-timers"] } # path = "/home/matthew/code/otherppl/embassy/embassy-main/embassy-executor" }
embassy-futures = { version = "0.1.1", features = ["defmt"] } # path = "/home/matthew/code/otherppl/embassy/embassy-main/embassy-futures" }
embassy-nrf = { version = "0.1.0", features = ["defmt", "time-driver-rtc1", "unstable-pac", "time", "gpiote"] } # path = "/home/matthew/code/otherppl/embassy/embassy-main/embassy-nrf" }
embassy-sync = { version = "0.5.0", features = ["defmt"] } # path = "/home/matthew/code/otherppl/embassy/embassy-main/embassy-sync" }
embassy-usb = { version = "0.1.0" } # path = "/home/matthew/code/otherppl/embassy/embassy-main/embassy-usb" } # , features = ["defmt"] }
embassy-time = { version = "0.3.0" } # path = "/home/matthew/code/otherppl/embassy/embassy-main/embassy-time" }
embassy-embedded-hal = { version = "0.1.0" } # path = "/home/matthew/code/otherppl/embassy/embassy-main/embassy-embedded-hal" }

defmt = "0.3.5"
defmt-rtt = "0.4.0"
panic-probe = { version = "0.3.1", features = ["print-defmt"] }
cortex-m-rt = "0.7.3"
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
embedded-hal = { version = "1.0.0", features = ["defmt-03"] }
static_cell = "2.0.0"
paj7025-nrf = { version = "0.1.0", path = "../paj7025-nrf" }







# embassy-time = { version = "0.1.3", path = "embassy/embassy/embassy-time", features = ["defmt", "defmt-timestamp-uptime"] }
# embedded-io = { version = "0.5.0", features = ["defmt-03"]  }
# embedded-io-async = { version = "0.5.0", optional = true, features = ["defmt-03"] }
# embassy-lora = { version = "0.1.0", path = "embassy/embassy/embassy-lora", features = ["time", "defmt"], optional = true }
# lora-phy = { version = "2", optional = true }
# lorawan-device = { version = "0.11.0", default-features = false, features = ["async", "external-lora-phy"], optional = true }
# lorawan = { version = "0.7.4", default-features = false, features = ["default-crypto"], optional = true }
# embassy-net-esp-hosted = { version = "0.1.0", path = "embassy/embassy/embassy-net-esp-hosted", features = ["defmt"], optional = true }
# embassy-net-enc28j60 = { version = "0.1.0", path = "embassy/embassy/embassy-net-enc28j60", features = ["defmt"], optional = true }

# defmt = "0.3"
# defmt-rtt = "0.4"

# fixed = "1.10.0"
# static_cell = "1.1"
# cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
# cortex-m-rt = "0.7.0"
# panic-probe = { version = "0.3", features = ["print-defmt"] }
# futures = { version = "0.3.17", default-features = false, features = ["async-await"] }
# rand = { version = "0.8.4", default-features = false }
# embedded-storage = "0.3.0"
# usbd-hid = "0.6.0"
# serde = { version = "1.0.136", default-features = false }
# embedded-hal = { version = "1.0.0-rc.1" }
# embedded-hal-async = { version = "1.0.0-rc.1", optional = true }
# embedded-hal-bus = { version = "0.1.0-rc.1" }
# num-integer = { version = "0.1.45", default-features = false }
# microfft = "0.5.0"

# nrf-softdevice = { path = "embassy/nrf-softdevice/nrf-softdevice", features = ["nightly", "s140", "nrf52840", "ble-peripheral", "ble-gatt-server", "defmt"] }

[profile.release]
debug = 2
