# VM (nRF5340, M33F)
[target.thumbv8m.main-none-eabihf]
rustflags = '-C target-cpu=cortex-m33 --cfg context="atslite1"'
runner = "probe-rs run --chip nRF5340_xxAA"

# ATS Lite 1 (nRF52840, M4F)
[target.thumbv7em-none-eabihf]
rustflags = '-C target-cpu=cortex-m4 --cfg context="vm"'
runner = "probe-rs run --chip nRF52840_xxAA"

[build]
# Choose ONE depending on what you’re working on:
target = "thumbv8m.main-none-eabihf"
# target = "thumbv7em-none-eabihf"

# Uncomment to see flash/memory usage report
# [env]
# RUSTC_LOG = "rustc_codegen_ssa::back::link=info"

# [patch."https://github.com/odysseyarm/ats_common"]
# ats_common = { path = "patch/ats_common" }
#
[patch."https://github.com/odysseyarm/protodonge-rs"]
protodongers = { path = "patch/protodonge-rs" }

# [patch."https://github.com/0e4ef622/icm426xx"]
# icm426xx = { path = "patch/icm426xx" }

# [patch."https://github.com/Abrahamh08/bmi2"]
# bmi2 = { path = "../../../../forks/bmi2" }

[patch.crates-io]
# embassy-nrf = { path = "../../../../forks/embassy/embassy-nrf" }
# embassy-time-driver = { path = "../../../../forks/embassy/embassy-time-driver" }
# embassy-usb-driver = { path = "../../../../forks/embassy/embassy-usb-driver" }
# embassy-executor = { path = "../../../../forks/embassy/embassy-executor" }
# embassy-time = { path = "../../../../forks/embassy/embassy-time" }
embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy" }

[env]
DEFMT_LOG = "info"
