[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-rs chip list`
runner = "cargo bin probe-rs run --chip nRF5340_xxAA"

[build]
target = "thumbv8m.main-none-eabihf"
rustflags = "-C target-cpu=cortex-m33"

[env]
RUSTC_LOG = "rustc_codegen_ssa::back::link=info"

# [patch."https://github.com/odysseyarm/ats_common"]
# ats_common = { path = "../../ats_common/ats_common" }
#
# [patch."https://github.com/odysseyarm/protodonge-rs"]
# protodongers = { path = "../../protodonge-rs" }
