[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-rs chip list`
runner = "cargo bin probe-rs run --chip nRF5340_xxAA"

[build]
target = "thumbv8m.main-none-eabihf"
rustflags = "-C target-cpu=cortex-m33"

# Uncomment to see flash/memory usage report
# [env]
# RUSTC_LOG = "rustc_codegen_ssa::back::link=info"

# [patch."https://github.com/odysseyarm/ats_common"]
# ats_common = { path = "patch/ats_common" }
#
# [patch."https://github.com/odysseyarm/protodonge-rs"]
# protodongers = { path = "patch/protodonge-rs" }

# [patch."https://github.com/0e4ef622/icm426xx"]
# icm426xx = { path = "patch/icm426xx" }

# [patch."https://github.com/embassy-rs/embassy.git"]
# embassy-executor = { path = "patch/embassy/embassy-executor" }
# embassy-embedded-hal = { path = "patch/embassy/embassy-embedded-hal" }
# embassy-futures = { path = "patch/embassy/embassy-futures" }
# embassy-nrf = { path = "patch/embassy/embassy-nrf" }
# embassy-boot = { path = "patch/embassy/embassy-boot" }
# embassy-sync = { path = "patch/embassy/embassy-sync" }
# embassy-time = { path = "patch/embassy/embassy-time" }
# embassy-usb = { path = "patch/embassy/embassy-usb" }
# embassy-usb-dfu = { path = "patch/embassy/embassy-usb-dfu" }
